version: 2
jobs:
  build:
    environment:
      COVERALLS_REPO_TOKEN: YbJqokvG5PNhxyUXqUG7IXmHqvbnk2mid
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - save_cache: 
          key: dependency-cache-v2-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Test and Coverage
          command: |
            npm test
            npm run coveralls
